# Generated by Django 4.2.1 on 2023-05-31 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_event_last_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title']},
        ),
    ]
