# Generated by Django 4.2.2 on 2023-06-08 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_cart_user_cart_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='product.cart'),
        ),
        migrations.DeleteModel(
            name='UserCart',
        ),
    ]
