# Generated by Django 4.2.1 on 2023-05-31 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('location', '0002_location_city_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='content_type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='location',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
